### ISSUE TITLE
Disabling user registration does not work

### ISSUE THREAD

**Issue by vStone** [rlidwka/sinopia-htpasswd#3]
config:

```
auth:
  htpasswd:
    file: /data/sinopia/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to 0 to disable registration.
    max_users: 0
```

adduser:

```
[vagrant@nodejs ~]$ npm adduser
Username: xxx
Password: 
Email: (this IS public) xxx@xxx.be
```

Result:

```
tail -n1 /data/sinopia/htpasswd
xxx:$6$enUFPJHfZdQUxA==$nRt6buDmJKbGeLIIrX50xVrZHNfv2y3SxVBscLsvdHs.XMHdPjr3sDN/2hFTYUf5j3.Q0R4daxt79tyw9Phul0:autocreated 2014-09-26T11:11:01.807Z
```
